# try igraph

```{r load_library, echo=FALSE, message=FALSE, results='markup'}
library(igraph)
library(ggplot2)
library(scales)
library(reshape)
library(pander)

centrality.norm<-function(graph,type=c("degree","closeness","betweenness"),centralization=FALSE)
    {    
    result<-NA
    g<-graph
    cent<-centralization
    if (!is.igraph(g)) {stop("Not a graph object")}
    if (type[[1]] == "degree") {
        if (!cent) result <- degree(g)/(vcount(g)-1)
        else result <- (sum(max(degree(g))-degree(g)))/((vcount(g)-1)*(vcount(g)-2))}
    else if (type[[1]] == "betweenness") {
        temp <- 2*betweenness(g)/((vcount(g)-1)*(vcount(g)-2))
        if (!cent) result <- temp
        else  result <- sum(max(temp)-temp)/(vcount(g)-1)}
    else if (type[[1]] == "closeness") {
        if (!cent) result <- closeness(g)
        else result <- (2*vcount(g)-3)*(sum(max(closeness(g))-closeness(g)))/((vcount(g)-1)*(vcount(g)-2))}
    else {stop("this type is unavailable or mispelled")}
    return(result)
    }

file_match <- "d:/data/alignment/self_alignment/S288Cvsselfalign.match.tsv"
file_match

mydata_match <- read.csv(file_match, header=F, sep="\t")
mydata_match <- mydata_match[c(1,2)] # keep the first two columns

file_blast <- "d:/data/alignment/self_alignment/S288Cvsselfalign.blast.tsv"
file_blast

mydata_blast <- read.csv(file_blast, header=F, sep="\t")
mydata_blast <- mydata_blast[c(1,2)] # keep the first two columns

g <- graph.data.frame(rbind(mydata_match, mydata_blast), directed=F)
```


```{r graph_properties, echo=FALSE, results="markup"}
ecount(g)
vcount(g)

# network diameter
diameter(g)

# show the farthest nodes
farthest.nodes(g)
```

```{r}
lc <- largest.cliques(g)
# create a new graph of the largest clique
V(g)$label <- V(g)$name
g.lc <- subgraph(g, lc[[1]])

plot(g.lc, layout=layout.fruchterman.reingold, vertex.color="gray60", vertex.size = 0, edge.arrow.size = 0.5, edge.color = "gray80")


```
